// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tekscan_server.proto

#include "tekscan_server.pb.h"
#include "tekscan_server.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace TekscanServerNamespace {

static const char* TekscanServer_method_names[] = {
  "/TekscanServerNamespace.TekscanServer/StartRecording",
  "/TekscanServerNamespace.TekscanServer/BreakRecording",
  "/TekscanServerNamespace.TekscanServer/GetForce",
};

std::unique_ptr< TekscanServer::Stub> TekscanServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TekscanServer::Stub> stub(new TekscanServer::Stub(channel));
  return stub;
}

TekscanServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartRecording_(TekscanServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BreakRecording_(TekscanServer_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetForce_(TekscanServer_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TekscanServer::Stub::StartRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::StartRecordingRequest& request, ::TekscanServerNamespace::SimpleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartRecording_, context, request, response);
}

void TekscanServer::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::StartRecordingRequest* request, ::TekscanServerNamespace::SimpleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, std::move(f));
}

void TekscanServer::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::StartRecordingRequest* request, ::TekscanServerNamespace::SimpleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::SimpleResponse>* TekscanServer::Stub::PrepareAsyncStartRecordingRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::StartRecordingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TekscanServerNamespace::SimpleResponse>::Create(channel_.get(), cq, rpcmethod_StartRecording_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::SimpleResponse>* TekscanServer::Stub::AsyncStartRecordingRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::StartRecordingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartRecordingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TekscanServer::Stub::BreakRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::TekscanServerNamespace::BreakRecordingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BreakRecording_, context, request, response);
}

void TekscanServer::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::BreakRecordingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, std::move(f));
}

void TekscanServer::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::BreakRecordingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::BreakRecordingResponse>* TekscanServer::Stub::PrepareAsyncBreakRecordingRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TekscanServerNamespace::BreakRecordingResponse>::Create(channel_.get(), cq, rpcmethod_BreakRecording_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::BreakRecordingResponse>* TekscanServer::Stub::AsyncBreakRecordingRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBreakRecordingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TekscanServer::Stub::GetForce(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::TekscanServerNamespace::ForceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetForce_, context, request, response);
}

void TekscanServer::Stub::experimental_async::GetForce(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::ForceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetForce_, context, request, response, std::move(f));
}

void TekscanServer::Stub::experimental_async::GetForce(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::ForceResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetForce_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::ForceResponse>* TekscanServer::Stub::PrepareAsyncGetForceRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TekscanServerNamespace::ForceResponse>::Create(channel_.get(), cq, rpcmethod_GetForce_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::TekscanServerNamespace::ForceResponse>* TekscanServer::Stub::AsyncGetForceRaw(::grpc::ClientContext* context, const ::TekscanServerNamespace::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetForceRaw(context, request, cq);
  result->StartCall();
  return result;
}

TekscanServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TekscanServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TekscanServer::Service, ::TekscanServerNamespace::StartRecordingRequest, ::TekscanServerNamespace::SimpleResponse>(
          [](TekscanServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TekscanServerNamespace::StartRecordingRequest* req,
             ::TekscanServerNamespace::SimpleResponse* resp) {
               return service->StartRecording(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TekscanServer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TekscanServer::Service, ::TekscanServerNamespace::SimpleRequest, ::TekscanServerNamespace::BreakRecordingResponse>(
          [](TekscanServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TekscanServerNamespace::SimpleRequest* req,
             ::TekscanServerNamespace::BreakRecordingResponse* resp) {
               return service->BreakRecording(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TekscanServer_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TekscanServer::Service, ::TekscanServerNamespace::SimpleRequest, ::TekscanServerNamespace::ForceResponse>(
          [](TekscanServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TekscanServerNamespace::SimpleRequest* req,
             ::TekscanServerNamespace::ForceResponse* resp) {
               return service->GetForce(ctx, req, resp);
             }, this)));
}

TekscanServer::Service::~Service() {
}

::grpc::Status TekscanServer::Service::StartRecording(::grpc::ServerContext* context, const ::TekscanServerNamespace::StartRecordingRequest* request, ::TekscanServerNamespace::SimpleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TekscanServer::Service::BreakRecording(::grpc::ServerContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::BreakRecordingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TekscanServer::Service::GetForce(::grpc::ServerContext* context, const ::TekscanServerNamespace::SimpleRequest* request, ::TekscanServerNamespace::ForceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TekscanServerNamespace

