# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import armMessages_pb2 as armMessages__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in armMessages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class armCommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.armReady = channel.unary_unary(
                '/armCommunication/armReady',
                request_serializer=armMessages__pb2.readyRequest.SerializeToString,
                response_deserializer=armMessages__pb2.readyResponse.FromString,
                _registered_method=True)
        self.armStatus = channel.unary_unary(
                '/armCommunication/armStatus',
                request_serializer=armMessages__pb2.statusRequest.SerializeToString,
                response_deserializer=armMessages__pb2.statusResponse.FromString,
                _registered_method=True)
        self.armControl = channel.unary_unary(
                '/armCommunication/armControl',
                request_serializer=armMessages__pb2.moveArm.SerializeToString,
                response_deserializer=armMessages__pb2.moveResponse.FromString,
                _registered_method=True)
        self.gripperOpen = channel.unary_unary(
                '/armCommunication/gripperOpen',
                request_serializer=armMessages__pb2.gripperRequest.SerializeToString,
                response_deserializer=armMessages__pb2.moveResponse.FromString,
                _registered_method=True)
        self.stopArm = channel.unary_unary(
                '/armCommunication/stopArm',
                request_serializer=armMessages__pb2.stopRequest.SerializeToString,
                response_deserializer=armMessages__pb2.moveResponse.FromString,
                _registered_method=True)
        self.armHome = channel.unary_unary(
                '/armCommunication/armHome',
                request_serializer=armMessages__pb2.moveHome.SerializeToString,
                response_deserializer=armMessages__pb2.moveResponse.FromString,
                _registered_method=True)
        self.armRotateMode = channel.unary_unary(
                '/armCommunication/armRotateMode',
                request_serializer=armMessages__pb2.rotationModeRequest.SerializeToString,
                response_deserializer=armMessages__pb2.statusResponse.FromString,
                _registered_method=True)
        self.armRotate = channel.unary_unary(
                '/armCommunication/armRotate',
                request_serializer=armMessages__pb2.rotateRequest.SerializeToString,
                response_deserializer=armMessages__pb2.rotateResponse.FromString,
                _registered_method=True)
        self.armFeedback = channel.unary_stream(
                '/armCommunication/armFeedback',
                request_serializer=armMessages__pb2.torqueRequest.SerializeToString,
                response_deserializer=armMessages__pb2.torqueResponse.FromString,
                _registered_method=True)


class armCommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def armReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def gripperOpen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopArm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armRotateMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armRotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def armFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_armCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'armReady': grpc.unary_unary_rpc_method_handler(
                    servicer.armReady,
                    request_deserializer=armMessages__pb2.readyRequest.FromString,
                    response_serializer=armMessages__pb2.readyResponse.SerializeToString,
            ),
            'armStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.armStatus,
                    request_deserializer=armMessages__pb2.statusRequest.FromString,
                    response_serializer=armMessages__pb2.statusResponse.SerializeToString,
            ),
            'armControl': grpc.unary_unary_rpc_method_handler(
                    servicer.armControl,
                    request_deserializer=armMessages__pb2.moveArm.FromString,
                    response_serializer=armMessages__pb2.moveResponse.SerializeToString,
            ),
            'gripperOpen': grpc.unary_unary_rpc_method_handler(
                    servicer.gripperOpen,
                    request_deserializer=armMessages__pb2.gripperRequest.FromString,
                    response_serializer=armMessages__pb2.moveResponse.SerializeToString,
            ),
            'stopArm': grpc.unary_unary_rpc_method_handler(
                    servicer.stopArm,
                    request_deserializer=armMessages__pb2.stopRequest.FromString,
                    response_serializer=armMessages__pb2.moveResponse.SerializeToString,
            ),
            'armHome': grpc.unary_unary_rpc_method_handler(
                    servicer.armHome,
                    request_deserializer=armMessages__pb2.moveHome.FromString,
                    response_serializer=armMessages__pb2.moveResponse.SerializeToString,
            ),
            'armRotateMode': grpc.unary_unary_rpc_method_handler(
                    servicer.armRotateMode,
                    request_deserializer=armMessages__pb2.rotationModeRequest.FromString,
                    response_serializer=armMessages__pb2.statusResponse.SerializeToString,
            ),
            'armRotate': grpc.unary_unary_rpc_method_handler(
                    servicer.armRotate,
                    request_deserializer=armMessages__pb2.rotateRequest.FromString,
                    response_serializer=armMessages__pb2.rotateResponse.SerializeToString,
            ),
            'armFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.armFeedback,
                    request_deserializer=armMessages__pb2.torqueRequest.FromString,
                    response_serializer=armMessages__pb2.torqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'armCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('armCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class armCommunication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def armReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armReady',
            armMessages__pb2.readyRequest.SerializeToString,
            armMessages__pb2.readyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armStatus',
            armMessages__pb2.statusRequest.SerializeToString,
            armMessages__pb2.statusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armControl',
            armMessages__pb2.moveArm.SerializeToString,
            armMessages__pb2.moveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def gripperOpen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/gripperOpen',
            armMessages__pb2.gripperRequest.SerializeToString,
            armMessages__pb2.moveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stopArm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/stopArm',
            armMessages__pb2.stopRequest.SerializeToString,
            armMessages__pb2.moveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armHome',
            armMessages__pb2.moveHome.SerializeToString,
            armMessages__pb2.moveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armRotateMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armRotateMode',
            armMessages__pb2.rotationModeRequest.SerializeToString,
            armMessages__pb2.statusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armRotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/armCommunication/armRotate',
            armMessages__pb2.rotateRequest.SerializeToString,
            armMessages__pb2.rotateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def armFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/armCommunication/armFeedback',
            armMessages__pb2.torqueRequest.SerializeToString,
            armMessages__pb2.torqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
