// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tekscan_server.proto

#include "tekscan_server.pb.h"
#include "tekscan_server.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* TekscanServerS_method_names[] = {
  "/TekscanServerS/StartRecording",
  "/TekscanServerS/BreakRecording",
};

std::unique_ptr< TekscanServerS::Stub> TekscanServerS::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TekscanServerS::Stub> stub(new TekscanServerS::Stub(channel));
  return stub;
}

TekscanServerS::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StartRecording_(TekscanServerS_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BreakRecording_(TekscanServerS_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TekscanServerS::Stub::StartRecording(::grpc::ClientContext* context, const ::StartRecordingRequest& request, ::SimpleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartRecording_, context, request, response);
}

void TekscanServerS::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::StartRecordingRequest* request, ::SimpleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, std::move(f));
}

void TekscanServerS::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SimpleResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, std::move(f));
}

void TekscanServerS::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::StartRecordingRequest* request, ::SimpleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, reactor);
}

void TekscanServerS::Stub::experimental_async::StartRecording(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SimpleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartRecording_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SimpleResponse>* TekscanServerS::Stub::AsyncStartRecordingRaw(::grpc::ClientContext* context, const ::StartRecordingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SimpleResponse>::Create(channel_.get(), cq, rpcmethod_StartRecording_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::SimpleResponse>* TekscanServerS::Stub::PrepareAsyncStartRecordingRaw(::grpc::ClientContext* context, const ::StartRecordingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SimpleResponse>::Create(channel_.get(), cq, rpcmethod_StartRecording_, context, request, false);
}

::grpc::Status TekscanServerS::Stub::BreakRecording(::grpc::ClientContext* context, const ::SimpleRequest& request, ::BreakRecordingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BreakRecording_, context, request, response);
}

void TekscanServerS::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::SimpleRequest* request, ::BreakRecordingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, std::move(f));
}

void TekscanServerS::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::BreakRecordingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, std::move(f));
}

void TekscanServerS::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::SimpleRequest* request, ::BreakRecordingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, reactor);
}

void TekscanServerS::Stub::experimental_async::BreakRecording(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::BreakRecordingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BreakRecording_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BreakRecordingResponse>* TekscanServerS::Stub::AsyncBreakRecordingRaw(::grpc::ClientContext* context, const ::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::BreakRecordingResponse>::Create(channel_.get(), cq, rpcmethod_BreakRecording_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::BreakRecordingResponse>* TekscanServerS::Stub::PrepareAsyncBreakRecordingRaw(::grpc::ClientContext* context, const ::SimpleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::BreakRecordingResponse>::Create(channel_.get(), cq, rpcmethod_BreakRecording_, context, request, false);
}

TekscanServerS::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TekscanServerS_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TekscanServerS::Service, ::StartRecordingRequest, ::SimpleResponse>(
          [](TekscanServerS::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::StartRecordingRequest* req,
             ::SimpleResponse* resp) {
               return service->StartRecording(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TekscanServerS_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TekscanServerS::Service, ::SimpleRequest, ::BreakRecordingResponse>(
          [](TekscanServerS::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::SimpleRequest* req,
             ::BreakRecordingResponse* resp) {
               return service->BreakRecording(ctx, req, resp);
             }, this)));
}

TekscanServerS::Service::~Service() {
}

::grpc::Status TekscanServerS::Service::StartRecording(::grpc::ServerContext* context, const ::StartRecordingRequest* request, ::SimpleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TekscanServerS::Service::BreakRecording(::grpc::ServerContext* context, const ::SimpleRequest* request, ::BreakRecordingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


