/*
 * For compilation see make.bat
 */

syntax = "proto3";

service CameraCommunicatorS {
  rpc SetFramerate (SetFramerateRequest) returns (SimpleResponse) {}
  rpc SetRecordingPeriod (SetRecordingPeriodRequest) returns (SimpleResponse) {}
  rpc SetReferenceCamera (SetReferenceCameraRequest) returns (SimpleResponse) {}
  rpc PrepareRecording (SimpleRequest) returns (SimpleResponse) {}
  rpc StartRecording (SimpleRequest) returns (SimpleResponse) {}
  rpc CaptureSingleImage (SimpleRequest) returns (SimpleResponse) {}
  rpc SetDirectory (SetDirectoryRequest) returns (SimpleResponse) {}
  rpc SetGain (SetGainRequest) returns (SimpleResponse) {}
  rpc SetExposure (SetExposureRequest) returns (SimpleResponse) {}
  rpc BreakRecording (SimpleRequest) returns (SimpleResponse) {}
}

message SimpleRequest {
    int32 code = 1;
}

message SimpleResponse {
    int32 code = 1;
    string description = 2;
}

message SetFramerateRequest {
    string desc = 1;
    double framerate = 2;
}

message SetRecordingPeriodRequest {
    double time = 1;
}

message SetReferenceCameraRequest {
    int32 serial = 1;
}

message SetDirectoryRequest {
    string directory = 1;
}

message SetGainRequest {
    double gain = 1;
    int32 gain_type = 2; // 0 for value-set, 1 for auto
}

message SetExposureRequest {
    double exposure = 1;
    int32 exposure_type = 2; // 0 for value-set, 1 for auto
}
