/*
 * For compilation see make.bat
 */

syntax = "proto3";

package TekscanServerNamespace;
option csharp_namespace = "TPSS";

service TekscanServer {
  rpc StartRecording (StartRecordingRequest) returns (SimpleResponse) {}
  rpc BreakRecording (SimpleRequest) returns (BreakRecordingResponse) {}
  rpc CheckSuccess (SimpleRequest) returns (SuccessResponse) {}
}

message SimpleRequest {
    int32 code = 1;
}

message SimpleResponse {
    int32 code = 1;
    string description = 2;
}

message StartRecordingRequest {
    int32 trialNum = 1;
}

message BreakRecordingResponse {
    int32 successLevel = 1;
    double forceLevel = 2;
}

message SuccessResponse {
    int32 success = 1;
}
