// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: armMessages.proto

#include "armMessages.pb.h"
#include "armMessages.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* armCommunication_method_names[] = {
  "/armCommunication/armStatus",
  "/armCommunication/armControl",
  "/armCommunication/armHome",
  "/armCommunication/armFeedback",
};

std::unique_ptr< armCommunication::Stub> armCommunication::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< armCommunication::Stub> stub(new armCommunication::Stub(channel));
  return stub;
}

armCommunication::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_armStatus_(armCommunication_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_armControl_(armCommunication_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_armHome_(armCommunication_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_armFeedback_(armCommunication_method_names[3], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status armCommunication::Stub::armStatus(::grpc::ClientContext* context, const ::statusRequest& request, ::statusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_armStatus_, context, request, response);
}

void armCommunication::Stub::experimental_async::armStatus(::grpc::ClientContext* context, const ::statusRequest* request, ::statusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_armStatus_, context, request, response, std::move(f));
}

void armCommunication::Stub::experimental_async::armStatus(::grpc::ClientContext* context, const ::statusRequest* request, ::statusResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_armStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::statusResponse>* armCommunication::Stub::PrepareAsyncarmStatusRaw(::grpc::ClientContext* context, const ::statusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::statusResponse>::Create(channel_.get(), cq, rpcmethod_armStatus_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::statusResponse>* armCommunication::Stub::AsyncarmStatusRaw(::grpc::ClientContext* context, const ::statusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncarmStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status armCommunication::Stub::armControl(::grpc::ClientContext* context, const ::moveArm& request, ::moveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_armControl_, context, request, response);
}

void armCommunication::Stub::experimental_async::armControl(::grpc::ClientContext* context, const ::moveArm* request, ::moveResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_armControl_, context, request, response, std::move(f));
}

void armCommunication::Stub::experimental_async::armControl(::grpc::ClientContext* context, const ::moveArm* request, ::moveResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_armControl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::moveResponse>* armCommunication::Stub::PrepareAsyncarmControlRaw(::grpc::ClientContext* context, const ::moveArm& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::moveResponse>::Create(channel_.get(), cq, rpcmethod_armControl_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::moveResponse>* armCommunication::Stub::AsyncarmControlRaw(::grpc::ClientContext* context, const ::moveArm& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncarmControlRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status armCommunication::Stub::armHome(::grpc::ClientContext* context, const ::moveHome& request, ::moveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_armHome_, context, request, response);
}

void armCommunication::Stub::experimental_async::armHome(::grpc::ClientContext* context, const ::moveHome* request, ::moveResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_armHome_, context, request, response, std::move(f));
}

void armCommunication::Stub::experimental_async::armHome(::grpc::ClientContext* context, const ::moveHome* request, ::moveResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_armHome_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::moveResponse>* armCommunication::Stub::PrepareAsyncarmHomeRaw(::grpc::ClientContext* context, const ::moveHome& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::moveResponse>::Create(channel_.get(), cq, rpcmethod_armHome_, context, request, false);
}

::grpc::ClientAsyncResponseReader< ::moveResponse>* armCommunication::Stub::AsyncarmHomeRaw(::grpc::ClientContext* context, const ::moveHome& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncarmHomeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::torqueResponse>* armCommunication::Stub::armFeedbackRaw(::grpc::ClientContext* context, const ::torqueRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::torqueResponse>::Create(channel_.get(), rpcmethod_armFeedback_, context, request);
}

void armCommunication::Stub::experimental_async::armFeedback(::grpc::ClientContext* context, ::torqueRequest* request, ::grpc::experimental::ClientReadReactor< ::torqueResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::torqueResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_armFeedback_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::torqueResponse>* armCommunication::Stub::AsyncarmFeedbackRaw(::grpc::ClientContext* context, const ::torqueRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::torqueResponse>::Create(channel_.get(), cq, rpcmethod_armFeedback_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::torqueResponse>* armCommunication::Stub::PrepareAsyncarmFeedbackRaw(::grpc::ClientContext* context, const ::torqueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::torqueResponse>::Create(channel_.get(), cq, rpcmethod_armFeedback_, context, request, false, nullptr);
}

armCommunication::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      armCommunication_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< armCommunication::Service, ::statusRequest, ::statusResponse>(
          [](armCommunication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::statusRequest* req,
             ::statusResponse* resp) {
               return service->armStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      armCommunication_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< armCommunication::Service, ::moveArm, ::moveResponse>(
          [](armCommunication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::moveArm* req,
             ::moveResponse* resp) {
               return service->armControl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      armCommunication_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< armCommunication::Service, ::moveHome, ::moveResponse>(
          [](armCommunication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::moveHome* req,
             ::moveResponse* resp) {
               return service->armHome(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      armCommunication_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< armCommunication::Service, ::torqueRequest, ::torqueResponse>(
          [](armCommunication::Service* service,
             ::grpc::ServerContext* ctx,
             const ::torqueRequest* req,
             ::grpc::ServerWriter<::torqueResponse>* writer) {
               return service->armFeedback(ctx, req, writer);
             }, this)));
}

armCommunication::Service::~Service() {
}

::grpc::Status armCommunication::Service::armStatus(::grpc::ServerContext* context, const ::statusRequest* request, ::statusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status armCommunication::Service::armControl(::grpc::ServerContext* context, const ::moveArm* request, ::moveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status armCommunication::Service::armHome(::grpc::ServerContext* context, const ::moveHome* request, ::moveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status armCommunication::Service::armFeedback(::grpc::ServerContext* context, const ::torqueRequest* request, ::grpc::ServerWriter< ::torqueResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


