// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: armMessages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_armMessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_armMessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_armMessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_armMessages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[14]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_armMessages_2eproto;
class gripperRequest;
class gripperRequestDefaultTypeInternal;
extern gripperRequestDefaultTypeInternal _gripperRequest_default_instance_;
class moveArm;
class moveArmDefaultTypeInternal;
extern moveArmDefaultTypeInternal _moveArm_default_instance_;
class moveHome;
class moveHomeDefaultTypeInternal;
extern moveHomeDefaultTypeInternal _moveHome_default_instance_;
class moveResponse;
class moveResponseDefaultTypeInternal;
extern moveResponseDefaultTypeInternal _moveResponse_default_instance_;
class readyRequest;
class readyRequestDefaultTypeInternal;
extern readyRequestDefaultTypeInternal _readyRequest_default_instance_;
class readyResponse;
class readyResponseDefaultTypeInternal;
extern readyResponseDefaultTypeInternal _readyResponse_default_instance_;
class rotateRequest;
class rotateRequestDefaultTypeInternal;
extern rotateRequestDefaultTypeInternal _rotateRequest_default_instance_;
class rotateResponse;
class rotateResponseDefaultTypeInternal;
extern rotateResponseDefaultTypeInternal _rotateResponse_default_instance_;
class rotationModeRequest;
class rotationModeRequestDefaultTypeInternal;
extern rotationModeRequestDefaultTypeInternal _rotationModeRequest_default_instance_;
class statusRequest;
class statusRequestDefaultTypeInternal;
extern statusRequestDefaultTypeInternal _statusRequest_default_instance_;
class statusResponse;
class statusResponseDefaultTypeInternal;
extern statusResponseDefaultTypeInternal _statusResponse_default_instance_;
class stopRequest;
class stopRequestDefaultTypeInternal;
extern stopRequestDefaultTypeInternal _stopRequest_default_instance_;
class torqueRequest;
class torqueRequestDefaultTypeInternal;
extern torqueRequestDefaultTypeInternal _torqueRequest_default_instance_;
class torqueResponse;
class torqueResponseDefaultTypeInternal;
extern torqueResponseDefaultTypeInternal _torqueResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::gripperRequest* Arena::CreateMaybeMessage<::gripperRequest>(Arena*);
template<> ::moveArm* Arena::CreateMaybeMessage<::moveArm>(Arena*);
template<> ::moveHome* Arena::CreateMaybeMessage<::moveHome>(Arena*);
template<> ::moveResponse* Arena::CreateMaybeMessage<::moveResponse>(Arena*);
template<> ::readyRequest* Arena::CreateMaybeMessage<::readyRequest>(Arena*);
template<> ::readyResponse* Arena::CreateMaybeMessage<::readyResponse>(Arena*);
template<> ::rotateRequest* Arena::CreateMaybeMessage<::rotateRequest>(Arena*);
template<> ::rotateResponse* Arena::CreateMaybeMessage<::rotateResponse>(Arena*);
template<> ::rotationModeRequest* Arena::CreateMaybeMessage<::rotationModeRequest>(Arena*);
template<> ::statusRequest* Arena::CreateMaybeMessage<::statusRequest>(Arena*);
template<> ::statusResponse* Arena::CreateMaybeMessage<::statusResponse>(Arena*);
template<> ::stopRequest* Arena::CreateMaybeMessage<::stopRequest>(Arena*);
template<> ::torqueRequest* Arena::CreateMaybeMessage<::torqueRequest>(Arena*);
template<> ::torqueResponse* Arena::CreateMaybeMessage<::torqueResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class readyRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:readyRequest) */ {
 public:
  inline readyRequest() : readyRequest(nullptr) {}
  virtual ~readyRequest();

  readyRequest(const readyRequest& from);
  readyRequest(readyRequest&& from) noexcept
    : readyRequest() {
    *this = ::std::move(from);
  }

  inline readyRequest& operator=(const readyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline readyRequest& operator=(readyRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const readyRequest& default_instance();

  static inline const readyRequest* internal_default_instance() {
    return reinterpret_cast<const readyRequest*>(
               &_readyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(readyRequest& a, readyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(readyRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(readyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline readyRequest* New() const final {
    return CreateMaybeMessage<readyRequest>(nullptr);
  }

  readyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<readyRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const readyRequest& from);
  void MergeFrom(const readyRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(readyRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "readyRequest";
  }
  protected:
  explicit readyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:readyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class readyResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:readyResponse) */ {
 public:
  inline readyResponse() : readyResponse(nullptr) {}
  virtual ~readyResponse();

  readyResponse(const readyResponse& from);
  readyResponse(readyResponse&& from) noexcept
    : readyResponse() {
    *this = ::std::move(from);
  }

  inline readyResponse& operator=(const readyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline readyResponse& operator=(readyResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const readyResponse& default_instance();

  static inline const readyResponse* internal_default_instance() {
    return reinterpret_cast<const readyResponse*>(
               &_readyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(readyResponse& a, readyResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(readyResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(readyResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline readyResponse* New() const final {
    return CreateMaybeMessage<readyResponse>(nullptr);
  }

  readyResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<readyResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const readyResponse& from);
  void MergeFrom(const readyResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(readyResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "readyResponse";
  }
  protected:
  explicit readyResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:readyResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class statusRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:statusRequest) */ {
 public:
  inline statusRequest() : statusRequest(nullptr) {}
  virtual ~statusRequest();

  statusRequest(const statusRequest& from);
  statusRequest(statusRequest&& from) noexcept
    : statusRequest() {
    *this = ::std::move(from);
  }

  inline statusRequest& operator=(const statusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline statusRequest& operator=(statusRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const statusRequest& default_instance();

  static inline const statusRequest* internal_default_instance() {
    return reinterpret_cast<const statusRequest*>(
               &_statusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(statusRequest& a, statusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(statusRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(statusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline statusRequest* New() const final {
    return CreateMaybeMessage<statusRequest>(nullptr);
  }

  statusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<statusRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const statusRequest& from);
  void MergeFrom(const statusRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(statusRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "statusRequest";
  }
  protected:
  explicit statusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:statusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class statusResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:statusResponse) */ {
 public:
  inline statusResponse() : statusResponse(nullptr) {}
  virtual ~statusResponse();

  statusResponse(const statusResponse& from);
  statusResponse(statusResponse&& from) noexcept
    : statusResponse() {
    *this = ::std::move(from);
  }

  inline statusResponse& operator=(const statusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline statusResponse& operator=(statusResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const statusResponse& default_instance();

  static inline const statusResponse* internal_default_instance() {
    return reinterpret_cast<const statusResponse*>(
               &_statusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(statusResponse& a, statusResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(statusResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(statusResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline statusResponse* New() const final {
    return CreateMaybeMessage<statusResponse>(nullptr);
  }

  statusResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<statusResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const statusResponse& from);
  void MergeFrom(const statusResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(statusResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "statusResponse";
  }
  protected:
  explicit statusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:statusResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class gripperRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gripperRequest) */ {
 public:
  inline gripperRequest() : gripperRequest(nullptr) {}
  virtual ~gripperRequest();

  gripperRequest(const gripperRequest& from);
  gripperRequest(gripperRequest&& from) noexcept
    : gripperRequest() {
    *this = ::std::move(from);
  }

  inline gripperRequest& operator=(const gripperRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline gripperRequest& operator=(gripperRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const gripperRequest& default_instance();

  static inline const gripperRequest* internal_default_instance() {
    return reinterpret_cast<const gripperRequest*>(
               &_gripperRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(gripperRequest& a, gripperRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(gripperRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(gripperRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline gripperRequest* New() const final {
    return CreateMaybeMessage<gripperRequest>(nullptr);
  }

  gripperRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<gripperRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const gripperRequest& from);
  void MergeFrom(const gripperRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(gripperRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gripperRequest";
  }
  protected:
  explicit gripperRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWidthFieldNumber = 1,
  };
  // double width = 1;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // @@protoc_insertion_point(class_scope:gripperRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class stopRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:stopRequest) */ {
 public:
  inline stopRequest() : stopRequest(nullptr) {}
  virtual ~stopRequest();

  stopRequest(const stopRequest& from);
  stopRequest(stopRequest&& from) noexcept
    : stopRequest() {
    *this = ::std::move(from);
  }

  inline stopRequest& operator=(const stopRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline stopRequest& operator=(stopRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const stopRequest& default_instance();

  static inline const stopRequest* internal_default_instance() {
    return reinterpret_cast<const stopRequest*>(
               &_stopRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(stopRequest& a, stopRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(stopRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(stopRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline stopRequest* New() const final {
    return CreateMaybeMessage<stopRequest>(nullptr);
  }

  stopRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<stopRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const stopRequest& from);
  void MergeFrom(const stopRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(stopRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "stopRequest";
  }
  protected:
  explicit stopRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:stopRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class moveArm PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:moveArm) */ {
 public:
  inline moveArm() : moveArm(nullptr) {}
  virtual ~moveArm();

  moveArm(const moveArm& from);
  moveArm(moveArm&& from) noexcept
    : moveArm() {
    *this = ::std::move(from);
  }

  inline moveArm& operator=(const moveArm& from) {
    CopyFrom(from);
    return *this;
  }
  inline moveArm& operator=(moveArm&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const moveArm& default_instance();

  static inline const moveArm* internal_default_instance() {
    return reinterpret_cast<const moveArm*>(
               &_moveArm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(moveArm& a, moveArm& b) {
    a.Swap(&b);
  }
  inline void Swap(moveArm* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(moveArm* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline moveArm* New() const final {
    return CreateMaybeMessage<moveArm>(nullptr);
  }

  moveArm* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<moveArm>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const moveArm& from);
  void MergeFrom(const moveArm& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(moveArm* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "moveArm";
  }
  protected:
  explicit moveArm(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLateralFieldNumber = 1,
    kDepthFieldNumber = 2,
    kHeightFieldNumber = 3,
    kThetaFieldNumber = 4,
    kPhiFieldNumber = 5,
    kChiFieldNumber = 6,
    kWidthFieldNumber = 7,
  };
  // double lateral = 1;
  void clear_lateral();
  double lateral() const;
  void set_lateral(double value);
  private:
  double _internal_lateral() const;
  void _internal_set_lateral(double value);
  public:

  // double depth = 2;
  void clear_depth();
  double depth() const;
  void set_depth(double value);
  private:
  double _internal_depth() const;
  void _internal_set_depth(double value);
  public:

  // double height = 3;
  void clear_height();
  double height() const;
  void set_height(double value);
  private:
  double _internal_height() const;
  void _internal_set_height(double value);
  public:

  // double theta = 4;
  void clear_theta();
  double theta() const;
  void set_theta(double value);
  private:
  double _internal_theta() const;
  void _internal_set_theta(double value);
  public:

  // double phi = 5;
  void clear_phi();
  double phi() const;
  void set_phi(double value);
  private:
  double _internal_phi() const;
  void _internal_set_phi(double value);
  public:

  // double chi = 6;
  void clear_chi();
  double chi() const;
  void set_chi(double value);
  private:
  double _internal_chi() const;
  void _internal_set_chi(double value);
  public:

  // double width = 7;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // @@protoc_insertion_point(class_scope:moveArm)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double lateral_;
  double depth_;
  double height_;
  double theta_;
  double phi_;
  double chi_;
  double width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class moveHome PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:moveHome) */ {
 public:
  inline moveHome() : moveHome(nullptr) {}
  virtual ~moveHome();

  moveHome(const moveHome& from);
  moveHome(moveHome&& from) noexcept
    : moveHome() {
    *this = ::std::move(from);
  }

  inline moveHome& operator=(const moveHome& from) {
    CopyFrom(from);
    return *this;
  }
  inline moveHome& operator=(moveHome&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const moveHome& default_instance();

  static inline const moveHome* internal_default_instance() {
    return reinterpret_cast<const moveHome*>(
               &_moveHome_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(moveHome& a, moveHome& b) {
    a.Swap(&b);
  }
  inline void Swap(moveHome* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(moveHome* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline moveHome* New() const final {
    return CreateMaybeMessage<moveHome>(nullptr);
  }

  moveHome* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<moveHome>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const moveHome& from);
  void MergeFrom(const moveHome& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(moveHome* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "moveHome";
  }
  protected:
  explicit moveHome(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:moveHome)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class moveResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:moveResponse) */ {
 public:
  inline moveResponse() : moveResponse(nullptr) {}
  virtual ~moveResponse();

  moveResponse(const moveResponse& from);
  moveResponse(moveResponse&& from) noexcept
    : moveResponse() {
    *this = ::std::move(from);
  }

  inline moveResponse& operator=(const moveResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline moveResponse& operator=(moveResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const moveResponse& default_instance();

  static inline const moveResponse* internal_default_instance() {
    return reinterpret_cast<const moveResponse*>(
               &_moveResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(moveResponse& a, moveResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(moveResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(moveResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline moveResponse* New() const final {
    return CreateMaybeMessage<moveResponse>(nullptr);
  }

  moveResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<moveResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const moveResponse& from);
  void MergeFrom(const moveResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(moveResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "moveResponse";
  }
  protected:
  explicit moveResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseCodeFieldNumber = 1,
  };
  // int32 responseCode = 1;
  void clear_responsecode();
  ::PROTOBUF_NAMESPACE_ID::int32 responsecode() const;
  void set_responsecode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_responsecode() const;
  void _internal_set_responsecode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:moveResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 responsecode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class rotationModeRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rotationModeRequest) */ {
 public:
  inline rotationModeRequest() : rotationModeRequest(nullptr) {}
  virtual ~rotationModeRequest();

  rotationModeRequest(const rotationModeRequest& from);
  rotationModeRequest(rotationModeRequest&& from) noexcept
    : rotationModeRequest() {
    *this = ::std::move(from);
  }

  inline rotationModeRequest& operator=(const rotationModeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline rotationModeRequest& operator=(rotationModeRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const rotationModeRequest& default_instance();

  static inline const rotationModeRequest* internal_default_instance() {
    return reinterpret_cast<const rotationModeRequest*>(
               &_rotationModeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(rotationModeRequest& a, rotationModeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(rotationModeRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(rotationModeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline rotationModeRequest* New() const final {
    return CreateMaybeMessage<rotationModeRequest>(nullptr);
  }

  rotationModeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<rotationModeRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const rotationModeRequest& from);
  void MergeFrom(const rotationModeRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(rotationModeRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rotationModeRequest";
  }
  protected:
  explicit rotationModeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:rotationModeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class rotateRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rotateRequest) */ {
 public:
  inline rotateRequest() : rotateRequest(nullptr) {}
  virtual ~rotateRequest();

  rotateRequest(const rotateRequest& from);
  rotateRequest(rotateRequest&& from) noexcept
    : rotateRequest() {
    *this = ::std::move(from);
  }

  inline rotateRequest& operator=(const rotateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline rotateRequest& operator=(rotateRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const rotateRequest& default_instance();

  static inline const rotateRequest* internal_default_instance() {
    return reinterpret_cast<const rotateRequest*>(
               &_rotateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(rotateRequest& a, rotateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(rotateRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(rotateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline rotateRequest* New() const final {
    return CreateMaybeMessage<rotateRequest>(nullptr);
  }

  rotateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<rotateRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const rotateRequest& from);
  void MergeFrom(const rotateRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(rotateRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rotateRequest";
  }
  protected:
  explicit rotateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kTlFieldNumber = 2,
    kBlFieldNumber = 3,
    kTrFieldNumber = 4,
    kBrFieldNumber = 5,
    kDurationFieldNumber = 6,
  };
  // double speed = 1;
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // double tl = 2;
  void clear_tl();
  double tl() const;
  void set_tl(double value);
  private:
  double _internal_tl() const;
  void _internal_set_tl(double value);
  public:

  // double bl = 3;
  void clear_bl();
  double bl() const;
  void set_bl(double value);
  private:
  double _internal_bl() const;
  void _internal_set_bl(double value);
  public:

  // double tr = 4;
  void clear_tr();
  double tr() const;
  void set_tr(double value);
  private:
  double _internal_tr() const;
  void _internal_set_tr(double value);
  public:

  // double br = 5;
  void clear_br();
  double br() const;
  void set_br(double value);
  private:
  double _internal_br() const;
  void _internal_set_br(double value);
  public:

  // double duration = 6;
  void clear_duration();
  double duration() const;
  void set_duration(double value);
  private:
  double _internal_duration() const;
  void _internal_set_duration(double value);
  public:

  // @@protoc_insertion_point(class_scope:rotateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double speed_;
  double tl_;
  double bl_;
  double tr_;
  double br_;
  double duration_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class rotateResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rotateResponse) */ {
 public:
  inline rotateResponse() : rotateResponse(nullptr) {}
  virtual ~rotateResponse();

  rotateResponse(const rotateResponse& from);
  rotateResponse(rotateResponse&& from) noexcept
    : rotateResponse() {
    *this = ::std::move(from);
  }

  inline rotateResponse& operator=(const rotateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline rotateResponse& operator=(rotateResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const rotateResponse& default_instance();

  static inline const rotateResponse* internal_default_instance() {
    return reinterpret_cast<const rotateResponse*>(
               &_rotateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  friend void swap(rotateResponse& a, rotateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(rotateResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(rotateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline rotateResponse* New() const final {
    return CreateMaybeMessage<rotateResponse>(nullptr);
  }

  rotateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<rotateResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const rotateResponse& from);
  void MergeFrom(const rotateResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(rotateResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rotateResponse";
  }
  protected:
  explicit rotateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAngleFieldNumber = 1,
    kFlagFieldNumber = 2,
  };
  // double angle = 1;
  void clear_angle();
  double angle() const;
  void set_angle(double value);
  private:
  double _internal_angle() const;
  void _internal_set_angle(double value);
  public:

  // int32 flag = 2;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:rotateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double angle_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class torqueRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:torqueRequest) */ {
 public:
  inline torqueRequest() : torqueRequest(nullptr) {}
  virtual ~torqueRequest();

  torqueRequest(const torqueRequest& from);
  torqueRequest(torqueRequest&& from) noexcept
    : torqueRequest() {
    *this = ::std::move(from);
  }

  inline torqueRequest& operator=(const torqueRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline torqueRequest& operator=(torqueRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const torqueRequest& default_instance();

  static inline const torqueRequest* internal_default_instance() {
    return reinterpret_cast<const torqueRequest*>(
               &_torqueRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  friend void swap(torqueRequest& a, torqueRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(torqueRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(torqueRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline torqueRequest* New() const final {
    return CreateMaybeMessage<torqueRequest>(nullptr);
  }

  torqueRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<torqueRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const torqueRequest& from);
  void MergeFrom(const torqueRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(torqueRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "torqueRequest";
  }
  protected:
  explicit torqueRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFlagFieldNumber = 1,
  };
  // int32 flag = 1;
  void clear_flag();
  ::PROTOBUF_NAMESPACE_ID::int32 flag() const;
  void set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_flag() const;
  void _internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:torqueRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// -------------------------------------------------------------------

class torqueResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:torqueResponse) */ {
 public:
  inline torqueResponse() : torqueResponse(nullptr) {}
  virtual ~torqueResponse();

  torqueResponse(const torqueResponse& from);
  torqueResponse(torqueResponse&& from) noexcept
    : torqueResponse() {
    *this = ::std::move(from);
  }

  inline torqueResponse& operator=(const torqueResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline torqueResponse& operator=(torqueResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const torqueResponse& default_instance();

  static inline const torqueResponse* internal_default_instance() {
    return reinterpret_cast<const torqueResponse*>(
               &_torqueResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  friend void swap(torqueResponse& a, torqueResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(torqueResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(torqueResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline torqueResponse* New() const final {
    return CreateMaybeMessage<torqueResponse>(nullptr);
  }

  torqueResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<torqueResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const torqueResponse& from);
  void MergeFrom(const torqueResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(torqueResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "torqueResponse";
  }
  protected:
  explicit torqueResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_armMessages_2eproto);
    return ::descriptor_table_armMessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJoint1FieldNumber = 1,
    kJoint2FieldNumber = 2,
    kJoint3FieldNumber = 3,
    kJoint4FieldNumber = 4,
    kJoint5FieldNumber = 5,
    kJoint6FieldNumber = 6,
    kEndpointFieldNumber = 7,
  };
  // double joint1 = 1;
  void clear_joint1();
  double joint1() const;
  void set_joint1(double value);
  private:
  double _internal_joint1() const;
  void _internal_set_joint1(double value);
  public:

  // double joint2 = 2;
  void clear_joint2();
  double joint2() const;
  void set_joint2(double value);
  private:
  double _internal_joint2() const;
  void _internal_set_joint2(double value);
  public:

  // double joint3 = 3;
  void clear_joint3();
  double joint3() const;
  void set_joint3(double value);
  private:
  double _internal_joint3() const;
  void _internal_set_joint3(double value);
  public:

  // double joint4 = 4;
  void clear_joint4();
  double joint4() const;
  void set_joint4(double value);
  private:
  double _internal_joint4() const;
  void _internal_set_joint4(double value);
  public:

  // double joint5 = 5;
  void clear_joint5();
  double joint5() const;
  void set_joint5(double value);
  private:
  double _internal_joint5() const;
  void _internal_set_joint5(double value);
  public:

  // double joint6 = 6;
  void clear_joint6();
  double joint6() const;
  void set_joint6(double value);
  private:
  double _internal_joint6() const;
  void _internal_set_joint6(double value);
  public:

  // double endpoint = 7;
  void clear_endpoint();
  double endpoint() const;
  void set_endpoint(double value);
  private:
  double _internal_endpoint() const;
  void _internal_set_endpoint(double value);
  public:

  // @@protoc_insertion_point(class_scope:torqueResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double joint1_;
  double joint2_;
  double joint3_;
  double joint4_;
  double joint5_;
  double joint6_;
  double endpoint_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_armMessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// readyRequest

// -------------------------------------------------------------------

// readyResponse

// int32 flag = 1;
inline void readyResponse::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 readyResponse::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 readyResponse::flag() const {
  // @@protoc_insertion_point(field_get:readyResponse.flag)
  return _internal_flag();
}
inline void readyResponse::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void readyResponse::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:readyResponse.flag)
}

// -------------------------------------------------------------------

// statusRequest

// int32 flag = 1;
inline void statusRequest::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 statusRequest::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 statusRequest::flag() const {
  // @@protoc_insertion_point(field_get:statusRequest.flag)
  return _internal_flag();
}
inline void statusRequest::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void statusRequest::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:statusRequest.flag)
}

// -------------------------------------------------------------------

// statusResponse

// int32 flag = 1;
inline void statusResponse::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 statusResponse::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 statusResponse::flag() const {
  // @@protoc_insertion_point(field_get:statusResponse.flag)
  return _internal_flag();
}
inline void statusResponse::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void statusResponse::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:statusResponse.flag)
}

// -------------------------------------------------------------------

// gripperRequest

// double width = 1;
inline void gripperRequest::clear_width() {
  width_ = 0;
}
inline double gripperRequest::_internal_width() const {
  return width_;
}
inline double gripperRequest::width() const {
  // @@protoc_insertion_point(field_get:gripperRequest.width)
  return _internal_width();
}
inline void gripperRequest::_internal_set_width(double value) {
  
  width_ = value;
}
inline void gripperRequest::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:gripperRequest.width)
}

// -------------------------------------------------------------------

// stopRequest

// -------------------------------------------------------------------

// moveArm

// double lateral = 1;
inline void moveArm::clear_lateral() {
  lateral_ = 0;
}
inline double moveArm::_internal_lateral() const {
  return lateral_;
}
inline double moveArm::lateral() const {
  // @@protoc_insertion_point(field_get:moveArm.lateral)
  return _internal_lateral();
}
inline void moveArm::_internal_set_lateral(double value) {
  
  lateral_ = value;
}
inline void moveArm::set_lateral(double value) {
  _internal_set_lateral(value);
  // @@protoc_insertion_point(field_set:moveArm.lateral)
}

// double depth = 2;
inline void moveArm::clear_depth() {
  depth_ = 0;
}
inline double moveArm::_internal_depth() const {
  return depth_;
}
inline double moveArm::depth() const {
  // @@protoc_insertion_point(field_get:moveArm.depth)
  return _internal_depth();
}
inline void moveArm::_internal_set_depth(double value) {
  
  depth_ = value;
}
inline void moveArm::set_depth(double value) {
  _internal_set_depth(value);
  // @@protoc_insertion_point(field_set:moveArm.depth)
}

// double height = 3;
inline void moveArm::clear_height() {
  height_ = 0;
}
inline double moveArm::_internal_height() const {
  return height_;
}
inline double moveArm::height() const {
  // @@protoc_insertion_point(field_get:moveArm.height)
  return _internal_height();
}
inline void moveArm::_internal_set_height(double value) {
  
  height_ = value;
}
inline void moveArm::set_height(double value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:moveArm.height)
}

// double theta = 4;
inline void moveArm::clear_theta() {
  theta_ = 0;
}
inline double moveArm::_internal_theta() const {
  return theta_;
}
inline double moveArm::theta() const {
  // @@protoc_insertion_point(field_get:moveArm.theta)
  return _internal_theta();
}
inline void moveArm::_internal_set_theta(double value) {
  
  theta_ = value;
}
inline void moveArm::set_theta(double value) {
  _internal_set_theta(value);
  // @@protoc_insertion_point(field_set:moveArm.theta)
}

// double phi = 5;
inline void moveArm::clear_phi() {
  phi_ = 0;
}
inline double moveArm::_internal_phi() const {
  return phi_;
}
inline double moveArm::phi() const {
  // @@protoc_insertion_point(field_get:moveArm.phi)
  return _internal_phi();
}
inline void moveArm::_internal_set_phi(double value) {
  
  phi_ = value;
}
inline void moveArm::set_phi(double value) {
  _internal_set_phi(value);
  // @@protoc_insertion_point(field_set:moveArm.phi)
}

// double chi = 6;
inline void moveArm::clear_chi() {
  chi_ = 0;
}
inline double moveArm::_internal_chi() const {
  return chi_;
}
inline double moveArm::chi() const {
  // @@protoc_insertion_point(field_get:moveArm.chi)
  return _internal_chi();
}
inline void moveArm::_internal_set_chi(double value) {
  
  chi_ = value;
}
inline void moveArm::set_chi(double value) {
  _internal_set_chi(value);
  // @@protoc_insertion_point(field_set:moveArm.chi)
}

// double width = 7;
inline void moveArm::clear_width() {
  width_ = 0;
}
inline double moveArm::_internal_width() const {
  return width_;
}
inline double moveArm::width() const {
  // @@protoc_insertion_point(field_get:moveArm.width)
  return _internal_width();
}
inline void moveArm::_internal_set_width(double value) {
  
  width_ = value;
}
inline void moveArm::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:moveArm.width)
}

// -------------------------------------------------------------------

// moveHome

// int32 flag = 1;
inline void moveHome::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 moveHome::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 moveHome::flag() const {
  // @@protoc_insertion_point(field_get:moveHome.flag)
  return _internal_flag();
}
inline void moveHome::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void moveHome::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:moveHome.flag)
}

// -------------------------------------------------------------------

// moveResponse

// int32 responseCode = 1;
inline void moveResponse::clear_responsecode() {
  responsecode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 moveResponse::_internal_responsecode() const {
  return responsecode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 moveResponse::responsecode() const {
  // @@protoc_insertion_point(field_get:moveResponse.responseCode)
  return _internal_responsecode();
}
inline void moveResponse::_internal_set_responsecode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  responsecode_ = value;
}
inline void moveResponse::set_responsecode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_responsecode(value);
  // @@protoc_insertion_point(field_set:moveResponse.responseCode)
}

// -------------------------------------------------------------------

// rotationModeRequest

// int32 flag = 1;
inline void rotationModeRequest::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rotationModeRequest::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rotationModeRequest::flag() const {
  // @@protoc_insertion_point(field_get:rotationModeRequest.flag)
  return _internal_flag();
}
inline void rotationModeRequest::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void rotationModeRequest::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:rotationModeRequest.flag)
}

// -------------------------------------------------------------------

// rotateRequest

// double speed = 1;
inline void rotateRequest::clear_speed() {
  speed_ = 0;
}
inline double rotateRequest::_internal_speed() const {
  return speed_;
}
inline double rotateRequest::speed() const {
  // @@protoc_insertion_point(field_get:rotateRequest.speed)
  return _internal_speed();
}
inline void rotateRequest::_internal_set_speed(double value) {
  
  speed_ = value;
}
inline void rotateRequest::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:rotateRequest.speed)
}

// double tl = 2;
inline void rotateRequest::clear_tl() {
  tl_ = 0;
}
inline double rotateRequest::_internal_tl() const {
  return tl_;
}
inline double rotateRequest::tl() const {
  // @@protoc_insertion_point(field_get:rotateRequest.tl)
  return _internal_tl();
}
inline void rotateRequest::_internal_set_tl(double value) {
  
  tl_ = value;
}
inline void rotateRequest::set_tl(double value) {
  _internal_set_tl(value);
  // @@protoc_insertion_point(field_set:rotateRequest.tl)
}

// double bl = 3;
inline void rotateRequest::clear_bl() {
  bl_ = 0;
}
inline double rotateRequest::_internal_bl() const {
  return bl_;
}
inline double rotateRequest::bl() const {
  // @@protoc_insertion_point(field_get:rotateRequest.bl)
  return _internal_bl();
}
inline void rotateRequest::_internal_set_bl(double value) {
  
  bl_ = value;
}
inline void rotateRequest::set_bl(double value) {
  _internal_set_bl(value);
  // @@protoc_insertion_point(field_set:rotateRequest.bl)
}

// double tr = 4;
inline void rotateRequest::clear_tr() {
  tr_ = 0;
}
inline double rotateRequest::_internal_tr() const {
  return tr_;
}
inline double rotateRequest::tr() const {
  // @@protoc_insertion_point(field_get:rotateRequest.tr)
  return _internal_tr();
}
inline void rotateRequest::_internal_set_tr(double value) {
  
  tr_ = value;
}
inline void rotateRequest::set_tr(double value) {
  _internal_set_tr(value);
  // @@protoc_insertion_point(field_set:rotateRequest.tr)
}

// double br = 5;
inline void rotateRequest::clear_br() {
  br_ = 0;
}
inline double rotateRequest::_internal_br() const {
  return br_;
}
inline double rotateRequest::br() const {
  // @@protoc_insertion_point(field_get:rotateRequest.br)
  return _internal_br();
}
inline void rotateRequest::_internal_set_br(double value) {
  
  br_ = value;
}
inline void rotateRequest::set_br(double value) {
  _internal_set_br(value);
  // @@protoc_insertion_point(field_set:rotateRequest.br)
}

// double duration = 6;
inline void rotateRequest::clear_duration() {
  duration_ = 0;
}
inline double rotateRequest::_internal_duration() const {
  return duration_;
}
inline double rotateRequest::duration() const {
  // @@protoc_insertion_point(field_get:rotateRequest.duration)
  return _internal_duration();
}
inline void rotateRequest::_internal_set_duration(double value) {
  
  duration_ = value;
}
inline void rotateRequest::set_duration(double value) {
  _internal_set_duration(value);
  // @@protoc_insertion_point(field_set:rotateRequest.duration)
}

// -------------------------------------------------------------------

// rotateResponse

// double angle = 1;
inline void rotateResponse::clear_angle() {
  angle_ = 0;
}
inline double rotateResponse::_internal_angle() const {
  return angle_;
}
inline double rotateResponse::angle() const {
  // @@protoc_insertion_point(field_get:rotateResponse.angle)
  return _internal_angle();
}
inline void rotateResponse::_internal_set_angle(double value) {
  
  angle_ = value;
}
inline void rotateResponse::set_angle(double value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:rotateResponse.angle)
}

// int32 flag = 2;
inline void rotateResponse::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rotateResponse::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rotateResponse::flag() const {
  // @@protoc_insertion_point(field_get:rotateResponse.flag)
  return _internal_flag();
}
inline void rotateResponse::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void rotateResponse::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:rotateResponse.flag)
}

// -------------------------------------------------------------------

// torqueRequest

// int32 flag = 1;
inline void torqueRequest::clear_flag() {
  flag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 torqueRequest::_internal_flag() const {
  return flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 torqueRequest::flag() const {
  // @@protoc_insertion_point(field_get:torqueRequest.flag)
  return _internal_flag();
}
inline void torqueRequest::_internal_set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  flag_ = value;
}
inline void torqueRequest::set_flag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:torqueRequest.flag)
}

// -------------------------------------------------------------------

// torqueResponse

// double joint1 = 1;
inline void torqueResponse::clear_joint1() {
  joint1_ = 0;
}
inline double torqueResponse::_internal_joint1() const {
  return joint1_;
}
inline double torqueResponse::joint1() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint1)
  return _internal_joint1();
}
inline void torqueResponse::_internal_set_joint1(double value) {
  
  joint1_ = value;
}
inline void torqueResponse::set_joint1(double value) {
  _internal_set_joint1(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint1)
}

// double joint2 = 2;
inline void torqueResponse::clear_joint2() {
  joint2_ = 0;
}
inline double torqueResponse::_internal_joint2() const {
  return joint2_;
}
inline double torqueResponse::joint2() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint2)
  return _internal_joint2();
}
inline void torqueResponse::_internal_set_joint2(double value) {
  
  joint2_ = value;
}
inline void torqueResponse::set_joint2(double value) {
  _internal_set_joint2(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint2)
}

// double joint3 = 3;
inline void torqueResponse::clear_joint3() {
  joint3_ = 0;
}
inline double torqueResponse::_internal_joint3() const {
  return joint3_;
}
inline double torqueResponse::joint3() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint3)
  return _internal_joint3();
}
inline void torqueResponse::_internal_set_joint3(double value) {
  
  joint3_ = value;
}
inline void torqueResponse::set_joint3(double value) {
  _internal_set_joint3(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint3)
}

// double joint4 = 4;
inline void torqueResponse::clear_joint4() {
  joint4_ = 0;
}
inline double torqueResponse::_internal_joint4() const {
  return joint4_;
}
inline double torqueResponse::joint4() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint4)
  return _internal_joint4();
}
inline void torqueResponse::_internal_set_joint4(double value) {
  
  joint4_ = value;
}
inline void torqueResponse::set_joint4(double value) {
  _internal_set_joint4(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint4)
}

// double joint5 = 5;
inline void torqueResponse::clear_joint5() {
  joint5_ = 0;
}
inline double torqueResponse::_internal_joint5() const {
  return joint5_;
}
inline double torqueResponse::joint5() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint5)
  return _internal_joint5();
}
inline void torqueResponse::_internal_set_joint5(double value) {
  
  joint5_ = value;
}
inline void torqueResponse::set_joint5(double value) {
  _internal_set_joint5(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint5)
}

// double joint6 = 6;
inline void torqueResponse::clear_joint6() {
  joint6_ = 0;
}
inline double torqueResponse::_internal_joint6() const {
  return joint6_;
}
inline double torqueResponse::joint6() const {
  // @@protoc_insertion_point(field_get:torqueResponse.joint6)
  return _internal_joint6();
}
inline void torqueResponse::_internal_set_joint6(double value) {
  
  joint6_ = value;
}
inline void torqueResponse::set_joint6(double value) {
  _internal_set_joint6(value);
  // @@protoc_insertion_point(field_set:torqueResponse.joint6)
}

// double endpoint = 7;
inline void torqueResponse::clear_endpoint() {
  endpoint_ = 0;
}
inline double torqueResponse::_internal_endpoint() const {
  return endpoint_;
}
inline double torqueResponse::endpoint() const {
  // @@protoc_insertion_point(field_get:torqueResponse.endpoint)
  return _internal_endpoint();
}
inline void torqueResponse::_internal_set_endpoint(double value) {
  
  endpoint_ = value;
}
inline void torqueResponse::set_endpoint(double value) {
  _internal_set_endpoint(value);
  // @@protoc_insertion_point(field_set:torqueResponse.endpoint)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_armMessages_2eproto
